<a href="https://colab.research.google.com/github/ShashankSatyam/American-Express-Churn-Prediction/blob/main/American_Express_Customer_Churn_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

In [ ]:

df = pd.read_csv('/content/American Express.csv')

In [ ]:
df.head()

Credit Score  Geography  Gender   Age  Customer Since  Current Account  \
0         553.0      Delhi  Female  45.0             4.0            0.000   
1         447.0  Bengaluru    Male  31.0             7.0            0.000   
2         501.0      Delhi  Female  32.0             2.0            0.000   
3         428.0      Delhi    Male  51.0             3.0            0.000   
4         492.0      Delhi  Female  57.0             6.0      1912681.501   

   Num of products  UPI Enabled  Estimated Yearly Income  Closed  
0              4.0          1.0                 274150.0     0.0  
1              4.0          1.0                 519360.0     0.0  
2              4.0          1.0                 545501.0     0.0  
3              4.0          1.0                  86868.0     0.0  
4              2.0          1.0                 518680.0     0.0

In [ ]:
df.isnull().sum()

Credit Score               2
Geography                  2
Gender                     2
Age                        2
Customer Since             2
Current Account            2
Num of products            2
UPI Enabled                2
Estimated Yearly Income    2
Closed                     2
dtype: int64

In [ ]:
df.dropna(inplace=True)


In [ ]:
df.isnull().sum()

Credit Score               0
Geography                  0
Gender                     0
Age                        0
Customer Since             0
Current Account            0
Num of products            0
UPI Enabled                0
Estimated Yearly Income    0
Closed                     0
dtype: int64

In [ ]:
# doing this now so that no null values remain in the dataset

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(X)
print(y)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 'Female' ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 'Female' ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]]
[0. 0. 0. ... 0. 1. 0.]


In [ ]:
df.shape

(9927, 10)

In [ ]:
X.shape

(9927, 9)

In [ ]:
y.shape

(9927,)

In [ ]:
# Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train.shape

(7941, 11)

In [ ]:
# ANN
# initialising the model

ann = tf.keras.models.Sequential()


In [ ]:
# adding first layer

ann.add(tf.keras.layers.Dense(units = 5 , activation='relu'))

In [ ]:
# adding first hidden layer

ann.add(tf.keras.layers.Dense(units = 5 , activation='relu'))

In [ ]:
# output layer

ann.add(tf.keras.layers.Dense(units = 1 , activation='sigmoid'))

In [ ]:
# have to read more about optimiser

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# trainning

ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 4s 4ms/step - loss: 0.4979 - accuracy: 0.7966
Epoch 2/120
249/249 [==============================] - 1s 5ms/step - loss: 0.4615 - accuracy: 0.7966
Epoch 3/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4395 - accuracy: 0.7966
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4288 - accuracy: 0.7966
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4234 - accuracy: 0.7966
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.7966
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4162 - accuracy: 0.7966
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4134 - accuracy: 0.7966
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4104 - accuracy: 0.7966
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4080 - accura

In [ ]:
#  Predicting for a single instance

print (ann.predict(sc.transform([[1, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 156ms/step
[[False]]


In [ ]:
# Prediction on testset

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

'''This line converts the predicted probabilities into binary predictions.
If the predicted probability is greater than 0.5, the prediction is True (or 1). Otherwise, it is False (or 0).'''

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

'''This line concatenates the binary predictions (y_pred) with the actual test labels (y_test).
Both y_pred and y_test are reshaped to ensure they are 2-dimensional arrays with one column each. Finally,
the concatenated array is printed, showing the predicted and actual labels side by side for each test sample.'''

63/63 [==============================] - 0s 1ms/step
[[0. 1.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 1.]
 [0. 0.]
 [1. 1.]]


In [ ]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1501   72]
 [ 218  195]]


0.8539778449144008